"""Append new signal research candidates to backlog."""
import json

candidates = [
    {"date":"2026-05-25","name":"btc_gold_correlation_regime","asset_class":"cross-asset","target_assets":["BTC-USD","XAU-USD"],"category":"intermarket","description":"30-day rolling Pearson correlation between BTC and Gold daily returns as regime signal. Below -0.48 historically preceded sharp BTC rallies within 2-4 weeks. Current -0.88 is near record extreme. Mean-reverts reliably.","formula":"corr_30d = pearson(btc_returns[-30:], gold_returns[-30:]). z = (corr_30d - mean_252d) / std_252d. BUY BTC when z < -2.0. SELL when z > 1.5.","data_sources":["ohlcv"],"parameters":{"corr_window":30,"z_lookback":252,"buy_z":-2.0,"sell_z":1.5},"novelty_score":8.0,"edge_evidence":7.0,"data_availability":10.0,"implementation_cost":9.0,"non_redundancy":8.0,"composite_score":8.05,"source_url":"https://mudrex.com/learn/bitcoin-gold-correlation-coefficient-2026/","source_type":"industry","citation":"Mudrex BTC-Gold correlation 2026; CryptoRank; arxiv 2512.12815","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"oi_funding_quadrant","asset_class":"crypto","target_assets":["BTC-USD","ETH-USD"],"category":"microstructure","description":"4-quadrant: OI direction x FR sign. Extreme Q1 (OI>5%/day, FR>3%/day) = contrarian SHORT within 1-5 days. Q4 (OI down>15%, FR negative 2+ days) = contrarian LONG. 2523 days analyzed.","formula":"oi_pct = delta_oi/oi. quadrant = classify(oi_pct>0, fr>0). Extreme: oi_pct>0.05 AND fr>0.03 = SHORT.","data_sources":["binance_fapi"],"parameters":{"extreme_oi":0.05,"extreme_fr":0.03,"capitulation_drop":0.15},"novelty_score":7.0,"edge_evidence":7.0,"data_availability":9.0,"implementation_cost":7.0,"non_redundancy":7.0,"composite_score":7.25,"source_url":"https://axeladlerjr.com/bitcoin-open-interest-funding-rate/","source_type":"industry","citation":"Axel Adler Jr, 2523-day BTC OI+FR analysis","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"comex_silver_stress","asset_class":"metals","target_assets":["XAG-USD"],"category":"fundamental","description":"COMEX Stress Index: coverage ratio (registered/OI, 40%), inventory trend (25%), paper leverage (20%), vault outflows (15%). Coverage <15% = Stress. Current 16.1% and tightening.","formula":"coverage = registered / OI. stress = weighted_composite. BUY when stress > 60.","data_sources":["cme_daily_metal_stocks"],"parameters":{"stress_threshold":60,"coverage_stress":0.15},"novelty_score":9.0,"edge_evidence":7.0,"data_availability":5.0,"implementation_cost":5.0,"non_redundancy":9.0,"composite_score":7.35,"source_url":"https://goldsilver.ai/metal-prices/comex-silver","source_type":"industry","citation":"GoldSilver.ai COMEX Monitor","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"kalshi_macro_bridge","asset_class":"cross-asset","target_assets":["BTC-USD","ETH-USD"],"category":"macro","description":"Kalshi prediction market daily probability changes forecast crypto vol. KXFED predicts BTC vol (t=3.63). KXRECSSNBER stable OOS. KXCPI predicts altcoin vol. Orthogonal to existing signals.","formula":"delta_prob = prob_today - prob_yesterday. vol_signal when abs(delta) > threshold.","data_sources":["kalshi_api"],"parameters":{"kxfed_threshold":0.02},"novelty_score":10.0,"edge_evidence":8.0,"data_availability":4.0,"implementation_cost":5.0,"non_redundancy":10.0,"composite_score":7.65,"source_url":"https://arxiv.org/abs/2604.01431","source_type":"academic","citation":"Mohanty & Krishnamachari 2026, arxiv 2604.01431","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"eth_usdt_netflow_directional","asset_class":"crypto","target_assets":["ETH-USD","BTC-USD"],"category":"onchain","description":"ETH net inflows to exchanges negatively predict ETH returns at 1-6h. USDT inflows positively predict BTC+ETH. Academic validation 2017-2023.","formula":"netflow_z = (netflow_6h - mean_30d) / std_30d. BUY when z < -1.5. SELL when z > 1.5.","data_sources":["cryptoquant_eth"],"parameters":{"z_buy":-1.5,"z_sell":1.5},"novelty_score":8.0,"edge_evidence":8.0,"data_availability":5.0,"implementation_cost":6.0,"non_redundancy":8.0,"composite_score":7.45,"source_url":"https://arxiv.org/abs/2411.06327","source_type":"academic","citation":"Chi, Chu, Hao 2024, arxiv 2411.06327","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"liquidation_cascade_detector","asset_class":"crypto","target_assets":["BTC-USD","ETH-USD"],"category":"microstructure","description":"4-module scoring (0-100): Volume (20pts), Keltner Exhaustion (30pts), Price Action (25pts), Higher TF Alignment (25pts). Fire at score>=45. Contrarian reversal.","formula":"total = vol_score + keltner_score + pa_score + tf_score. Signal when total >= 45.","data_sources":["ohlcv"],"parameters":{"score_threshold":45},"novelty_score":7.0,"edge_evidence":5.0,"data_availability":10.0,"implementation_cost":7.0,"non_redundancy":7.0,"composite_score":6.95,"source_url":"https://www.tradingview.com/script/9A7zNDKe/","source_type":"community","citation":"Cascade_Indicators TradingView","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"epu_gold_vol_predictor","asset_class":"metals","target_assets":["XAU-USD","XAG-USD"],"category":"macro","description":"EPU index as gold vol predictor via GARCH-MIDAS. Free from policyuncertainty.com. High EPU = higher gold vol. Scales MR confidence up, trend confidence down.","formula":"epu_z = (epu - sma_12m) / std_12m. vol_regime = high if z>1.","data_sources":["policyuncertainty_com"],"parameters":{"high_threshold":1.0},"novelty_score":8.0,"edge_evidence":7.0,"data_availability":7.0,"implementation_cost":7.0,"non_redundancy":8.0,"composite_score":7.5,"source_url":"https://www.aimspress.com/article/doi/10.3934/QFE.2026009","source_type":"academic","citation":"Qiao et al 2026, GARCH-MIDAS EPU+GVZ","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
    {"date":"2026-05-25","name":"silver_lease_rate_spike","asset_class":"metals","target_assets":["XAG-USD"],"category":"fundamental","description":"Silver lease rate as physical tightness early-warning. Spikes preceded 40-140% rallies. Lead price by days-weeks. Current 6.3%.","formula":"lease_z = (rate - sma_90d) / std_90d. BUY when z > 2.0.","data_sources":["lbma_lease_rates"],"parameters":{"z_buy":2.0},"novelty_score":9.0,"edge_evidence":7.0,"data_availability":4.0,"implementation_cost":5.0,"non_redundancy":9.0,"composite_score":7.35,"source_url":"https://www.bullionvault.com/gold-news/","source_type":"industry","citation":"BullionVault; LBMA Alchemist","status":"new","created_at":"2026-05-25T22:00:00+00:00","updated_at":"2026-05-25T22:00:00+00:00"},
]

with open("data/signal_research_backlog.jsonl", "a") as f:
    for c in candidates:
        f.write(json.dumps(c) + "\n")

print(f"Appended {len(candidates)} candidates")
total = sum(1 for _ in open("data/signal_research_backlog.jsonl"))
print(f"Total backlog: {total}")
