#!/usr/bin/env python3
"""Snapshot today's live signal-enablement mechanisms into
portfolio/registry_defaults.py.

The finance-analyzer engine has 4 overlapping hardcoded enablement
mechanisms (DISABLED_SIGNALS, _DISABLED_SIGNAL_OVERRIDES,
_TICKER_DISABLED_BY_HORIZON, asset-class sets — see
docs/plans/2026-07-18-dashboard-redesign-and-modular-engine.md Phase 4).
This script captures their CURRENT behavior into a plain-data module that
portfolio/component_registry.py reads. It does not change any behavior —
run it, diff the output, regenerate whenever tickers.py / signal_engine.py
enablement dicts change.

Usage:
    .venv/bin/python scripts/gen_registry_defaults.py
    .venv/bin/black portfolio/registry_defaults.py
"""

from __future__ import annotations

import datetime as dt
import pprint
from pathlib import Path

from portfolio import signal_engine
from portfolio.tickers import (
    ALL_TICKERS,
    DISABLED_SIGNALS,
    GPU_SIGNALS,
    SIGNAL_NAMES,
    get_disabled_reason,
)

OUT_PATH = Path(__file__).resolve().parent.parent / "portfolio" / "registry_defaults.py"

_ASSET_RESTRICTIONS = {
    **dict.fromkeys(signal_engine._CRYPTO_ONLY_SIGNALS, "crypto_only"),
    **dict.fromkeys(signal_engine._METALS_ONLY_SIGNALS, "metals_only"),
    **dict.fromkeys(signal_engine._NON_STOCK_SIGNALS, "non_stock"),
}


def _build_signals() -> dict[str, dict]:
    """Global, per-signal metadata — independent of ticker/horizon."""
    return {
        name: {
            "disabled": name in DISABLED_SIGNALS,
            "disabled_reason": get_disabled_reason(name),
            "gpu": name in GPU_SIGNALS,
            "core": name in signal_engine.CORE_SIGNAL_NAMES,
            "shadow_llm": name in signal_engine._KNOWN_SHADOW_LLMS,
            "asset_class_restriction": _ASSET_RESTRICTIONS.get(name),
        }
        for name in SIGNAL_NAMES
    }


def _build_horizon_map() -> dict[str, dict[str, frozenset]]:
    """Mirror _TICKER_DISABLED_BY_HORIZON exactly (frozensets, same keys)."""
    return {
        horizon: {ticker: frozenset(sigs) for ticker, sigs in per_ticker.items()}
        for horizon, per_ticker in signal_engine._TICKER_DISABLED_BY_HORIZON.items()
    }


def main() -> None:
    tickers = tuple(sorted(ALL_TICKERS))
    horizons = tuple(sorted(signal_engine._VALID_HORIZON_KEYS - {"_default"}))
    signals = _build_signals()
    overrides = sorted(signal_engine._DISABLED_SIGNAL_OVERRIDES)
    horizon_map = _build_horizon_map()

    header = f'''"""GENERATED by scripts/gen_registry_defaults.py on {dt.date.today()} — regenerate, don't hand-edit.

Snapshot of the live signal-enablement behavior in portfolio.tickers /
portfolio.signal_engine, captured from:
  - tickers.SIGNAL_NAMES, DISABLED_SIGNALS, GPU_SIGNALS, get_disabled_reason()
  - signal_engine._DISABLED_SIGNAL_OVERRIDES, _TICKER_DISABLED_BY_HORIZON,
    _CRYPTO_ONLY_SIGNALS, _METALS_ONLY_SIGNALS, _NON_STOCK_SIGNALS,
    CORE_SIGNAL_NAMES, _KNOWN_SHADOW_LLMS

Read API: portfolio/component_registry.py. Application code should go
through that module (which also applies the data/control/registry_overrides.json
live overlay) rather than importing these dicts directly.
"""

TICKERS = {tickers!r}

# Horizon keys signal_engine._TICKER_DISABLED_BY_HORIZON recognizes, minus
# "_default" (which applies at every horizon and is folded in separately).
HORIZONS = {horizons!r}

# Per-signal global metadata — same for every ticker/horizon.
SIGNALS = {pprint.pformat(signals, sort_dicts=True, width=88)}

# (signal, ticker) pairs rescued from a global disable — mirrors
# signal_engine._DISABLED_SIGNAL_OVERRIDES.
DISABLED_SIGNAL_OVERRIDES = frozenset({overrides!r})

# Per-ticker/per-horizon force-HOLD exceptions. Mirrors
# signal_engine._TICKER_DISABLED_BY_HORIZON exactly: "_default" applies at
# every horizon; other keys ADD to "_default" for that horizon only.
TICKER_DISABLED_BY_HORIZON = {pprint.pformat(horizon_map, sort_dicts=True, width=88)}
'''
    OUT_PATH.write_text(header, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(signals)} signals, {len(overrides)} overrides)")


if __name__ == "__main__":
    main()
