@echo off
setlocal enabledelayedexpansion

REM ============================================================
REM  Cloudflare Tunnel Setup for Finance-Analyzer Dashboard
REM  Exposes localhost:5055 as bets.raanman.lol
REM ============================================================
REM
REM  Prerequisites:
REM    1. Cloudflare account with raanman.lol domain added
REM    2. Domain nameservers pointed to Cloudflare
REM
REM  This script will:
REM    - Install cloudflared (if not present)
REM    - Authenticate with Cloudflare
REM    - Create a tunnel named "finance-dashboard"
REM    - Configure DNS routing for bets.raanman.lol
REM    - Install cloudflared as a Windows service
REM
REM  Usage: Run this script once on the machine running the dashboard.
REM ============================================================

set TUNNEL_NAME=finance-dashboard
set HOSTNAME=bets.raanman.lol
set LOCAL_SERVICE=http://localhost:5055
set CONFIG_DIR=%USERPROFILE%\.cloudflared
set CONFIG_FILE=%CONFIG_DIR%\config.yml

echo.
echo ==========================================
echo  Cloudflare Tunnel Setup
echo  %HOSTNAME% -^> %LOCAL_SERVICE%
echo ==========================================
echo.

REM --- Step 1: Check/Install cloudflared ---
where cloudflared >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [1/6] cloudflared not found. Installing via winget...
    winget install --id Cloudflare.cloudflared --accept-package-agreements --accept-source-agreements
    if %ERRORLEVEL% neq 0 (
        echo.
        echo ERROR: winget install failed. Please install cloudflared manually:
        echo   https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/
        echo.
        echo After installing, re-run this script.
        goto :error
    )
    echo cloudflared installed successfully.
    echo NOTE: You may need to restart your terminal for cloudflared to be on PATH.
    echo.
) else (
    echo [1/6] cloudflared is already installed.
)

REM --- Step 2: Authenticate ---
echo.
echo [2/6] Authenticating with Cloudflare...
echo       A browser window will open. Select the raanman.lol zone.
echo.
cloudflared login
if %ERRORLEVEL% neq 0 (
    echo ERROR: Authentication failed. Please try again.
    goto :error
)
echo Authentication successful.

REM --- Step 3: Create tunnel ---
echo.
echo [3/6] Creating tunnel "%TUNNEL_NAME%"...
echo.

REM Check if tunnel already exists
cloudflared tunnel list 2>nul | findstr /C:"%TUNNEL_NAME%" >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo Tunnel "%TUNNEL_NAME%" already exists. Skipping creation.
) else (
    cloudflared tunnel create %TUNNEL_NAME%
    if %ERRORLEVEL% neq 0 (
        echo ERROR: Failed to create tunnel. It may already exist with a different name.
        echo Run: cloudflared tunnel list
        goto :error
    )
)

REM --- Step 4: Get tunnel ID and write config ---
echo.
echo [4/6] Writing tunnel configuration...

REM Extract tunnel ID
for /f "tokens=1" %%i in ('cloudflared tunnel list 2^>nul ^| findstr /C:"%TUNNEL_NAME%"') do set TUNNEL_ID=%%i

if "%TUNNEL_ID%"=="" (
    echo ERROR: Could not find tunnel ID. Please check: cloudflared tunnel list
    goto :error
)

echo       Tunnel ID: %TUNNEL_ID%

REM Find credentials file
set CRED_FILE=%CONFIG_DIR%\%TUNNEL_ID%.json
if not exist "%CRED_FILE%" (
    echo WARNING: Credentials file not found at %CRED_FILE%
    echo          You may need to specify it manually in the config.
)

REM Write config file
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
(
    echo # Cloudflare Tunnel config for finance-analyzer dashboard
    echo # Auto-generated by setup_tunnel.bat
    echo.
    echo tunnel: %TUNNEL_ID%
    echo credentials-file: %CRED_FILE%
    echo.
    echo ingress:
    echo   - hostname: %HOSTNAME%
    echo     service: %LOCAL_SERVICE%
    echo     originRequest:
    echo       noTLSVerify: true
    echo       connectTimeout: 30s
    echo   - service: http_status:404
) > "%CONFIG_FILE%"

echo       Config written to: %CONFIG_FILE%

REM --- Step 5: Configure DNS ---
echo.
echo [5/6] Configuring DNS route: %HOSTNAME% -^> tunnel...
cloudflared tunnel route dns %TUNNEL_NAME% %HOSTNAME%
if %ERRORLEVEL% neq 0 (
    echo WARNING: DNS route may already exist, or there was an error.
    echo          Check Cloudflare dashboard for a CNAME record: %HOSTNAME%
    echo          It should point to: %TUNNEL_ID%.cfargotunnel.com
)

REM --- Step 6: Install as Windows service ---
echo.
echo [6/6] Installing cloudflared as a Windows service...
echo       This requires Administrator privileges.
echo.

REM Check if already installed
sc query cloudflared >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo Service already exists. Stopping and updating...
    net stop cloudflared >nul 2>&1
    cloudflared service uninstall >nul 2>&1
)

cloudflared service install
if %ERRORLEVEL% neq 0 (
    echo.
    echo WARNING: Service install failed. You may need to run this script as Administrator.
    echo          Alternatively, run the tunnel manually:
    echo            cloudflared tunnel run %TUNNEL_NAME%
    echo.
) else (
    net start cloudflared
    echo Service installed and started.
)

REM --- Done ---
echo.
echo ==========================================
echo  Setup Complete!
echo ==========================================
echo.
echo  Dashboard URL: https://%HOSTNAME%
echo  Redirect URL:  https://raanman.lol/bets
echo.
echo  Tunnel name:   %TUNNEL_NAME%
echo  Tunnel ID:     %TUNNEL_ID%
echo  Config file:   %CONFIG_FILE%
echo.
echo  To check status:  cloudflared tunnel info %TUNNEL_NAME%
echo  To view logs:     cloudflared tunnel run %TUNNEL_NAME% (manual mode)
echo  To stop service:  net stop cloudflared
echo  To start service: net start cloudflared
echo.
goto :eof

:error
echo.
echo Setup failed. Please fix the error above and re-run.
exit /b 1
