@echo off
setlocal enabledelayedexpansion

REM ============================================================
REM  Cloudflare Tunnel Setup for Finance-Analyzer Dashboard
REM  Exposes localhost:5055 as bets.raanman.lol
REM ============================================================
REM
REM  Prerequisites:
REM    1. Cloudflare account with raanman.lol domain added
REM    2. Domain nameservers pointed to Cloudflare
REM
REM  This script will:
REM    - Install cloudflared (if not present)
REM    - Authenticate with Cloudflare
REM    - Create a tunnel named "finance-dashboard"
REM    - Configure DNS routing for bets.raanman.lol
REM    - Install cloudflared as a Windows service
REM
REM  Usage: Run this script once on the machine running the dashboard.
REM ============================================================

set TUNNEL_NAME=finance-dashboard
set HOSTNAME=bets.raanman.lol
set LOCAL_SERVICE=http://localhost:5055
set CONFIG_DIR=%USERPROFILE%\.cloudflared
set CONFIG_FILE=%CONFIG_DIR%\config.yml

echo.
echo ==========================================
echo  Cloudflare Tunnel Setup
echo  %HOSTNAME% -^> %LOCAL_SERVICE%
echo ==========================================
echo.

REM --- Safety gate: refuse to run if dashboard_token is empty ---
REM Added 2026-04-28: empty token = public dashboard exposes portfolio JSON,
REM trades, decisions to anyone with the URL. Force a token before tunneling.
REM History: dashboard auth is opt-in (backwards-compat), see dashboard/app.py
REM _get_dashboard_token + check_token. Empty token returns 200 to all callers.
set REPO_ROOT=%~dp0..
pushd "%REPO_ROOT%"
"%REPO_ROOT%\.venv\Scripts\python.exe" -c "import json,sys; cfg=json.load(open('config.json',encoding='utf-8')); t=cfg.get('dashboard_token') or ''; sys.exit(0 if len(t)>=16 else 1)"
if %ERRORLEVEL% neq 0 (
    echo ERROR: dashboard_token in config.json is empty or too short.
    echo        Refusing to expose dashboard publicly without auth.
    echo.
    echo        Generate one with:
    echo          .venv\Scripts\python.exe -c "import secrets; print(secrets.token_urlsafe(32))"
    echo        Then set it in config.json under "dashboard_token".
    popd
    goto :error
)
popd
echo [0/6] dashboard_token present — auth gate satisfied.

REM --- Step 1: Check/Install cloudflared ---
where cloudflared >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [1/6] cloudflared not found. Installing via winget...
    winget install --id Cloudflare.cloudflared --accept-package-agreements --accept-source-agreements
    if %ERRORLEVEL% neq 0 (
        echo.
        echo ERROR: winget install failed. Please install cloudflared manually:
        echo   https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/
        echo.
        echo After installing, re-run this script.
        goto :error
    )
    echo cloudflared installed successfully.
    echo NOTE: You may need to restart your terminal for cloudflared to be on PATH.
    echo.
) else (
    echo [1/6] cloudflared is already installed.
)

REM --- Step 2: Authenticate ---
echo.
echo [2/6] Authenticating with Cloudflare...
echo       A browser window will open. Select the raanman.lol zone.
echo.
cloudflared login
if %ERRORLEVEL% neq 0 (
    echo ERROR: Authentication failed. Please try again.
    goto :error
)
echo Authentication successful.

REM --- Step 3: Create tunnel ---
echo.
echo [3/6] Creating tunnel "%TUNNEL_NAME%"...
echo.

REM Check if tunnel already exists
cloudflared tunnel list 2>nul | findstr /C:"%TUNNEL_NAME%" >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo Tunnel "%TUNNEL_NAME%" already exists. Skipping creation.
) else (
    cloudflared tunnel create %TUNNEL_NAME%
    if %ERRORLEVEL% neq 0 (
        echo ERROR: Failed to create tunnel. It may already exist with a different name.
        echo Run: cloudflared tunnel list
        goto :error
    )
)

REM --- Step 4: Get tunnel ID and write config ---
echo.
echo [4/6] Writing tunnel configuration...

REM Extract tunnel ID
for /f "tokens=1" %%i in ('cloudflared tunnel list 2^>nul ^| findstr /C:"%TUNNEL_NAME%"') do set TUNNEL_ID=%%i

if "%TUNNEL_ID%"=="" (
    echo ERROR: Could not find tunnel ID. Please check: cloudflared tunnel list
    goto :error
)

echo       Tunnel ID: %TUNNEL_ID%

REM Find credentials file
set CRED_FILE=%CONFIG_DIR%\%TUNNEL_ID%.json
if not exist "%CRED_FILE%" (
    echo WARNING: Credentials file not found at %CRED_FILE%
    echo          You may need to specify it manually in the config.
)

REM Write config file
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
(
    echo # Cloudflare Tunnel config for finance-analyzer dashboard
    echo # Auto-generated by setup_tunnel.bat
    echo.
    echo tunnel: %TUNNEL_ID%
    echo credentials-file: %CRED_FILE%
    echo.
    echo ingress:
    echo   - hostname: %HOSTNAME%
    echo     service: %LOCAL_SERVICE%
    echo     originRequest:
    echo       noTLSVerify: true
    echo       connectTimeout: 30s
    echo   - service: http_status:404
) > "%CONFIG_FILE%"

echo       Config written to: %CONFIG_FILE%

REM --- Step 5: Configure DNS ---
echo.
echo [5/6] Configuring DNS route: %HOSTNAME% -^> tunnel...
cloudflared tunnel route dns %TUNNEL_NAME% %HOSTNAME%
if %ERRORLEVEL% neq 0 (
    echo WARNING: DNS route may already exist, or there was an error.
    echo          Check Cloudflare dashboard for a CNAME record: %HOSTNAME%
    echo          It should point to: %TUNNEL_ID%.cfargotunnel.com
)

REM --- Step 6: Install as Windows service ---
echo.
echo [6/6] Installing cloudflared as a Windows service...
echo       This requires Administrator privileges.
echo.

REM Uninstall any existing service so the ImagePath patch below applies to a
REM fresh registration (ImagePath isn't preserved on uninstall+install).
sc query cloudflared >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo Service already exists. Stopping and updating...
    net stop cloudflared >nul 2>&1
    cloudflared service uninstall >nul 2>&1
)

REM Copy config + credentials to LocalSystem's profile. Cloudflare's docs
REM require this; their `service install` does NOT do it automatically. The
REM service runs as LocalSystem, whose %USERPROFILE% is the systemprofile
REM directory (not the human user's profile), so without this copy the service
REM has no config to load and silently exits.
REM (Discovered 2026-04-30: bat shipped without this for ~5 weeks before it bit us.)
REM https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/as-a-service/windows/
set SYSPROFILE_DIR=%SystemRoot%\System32\config\systemprofile\.cloudflared
if not exist "%SYSPROFILE_DIR%" mkdir "%SYSPROFILE_DIR%"
copy /Y "%CONFIG_FILE%" "%SYSPROFILE_DIR%\config.yml" >nul
copy /Y "%CRED_FILE%" "%SYSPROFILE_DIR%\%TUNNEL_ID%.json" >nul
echo       Config + creds copied to %SYSPROFILE_DIR%

cloudflared service install
if %ERRORLEVEL% neq 0 (
    echo.
    echo WARNING: Service install failed. You may need to run this script as Administrator.
    echo          Alternatively, run the tunnel manually:
    echo            cloudflared tunnel run %TUNNEL_NAME%
    echo.
    goto :eof
)

REM Patch the service's ImagePath to include the tunnel-run command.
REM `cloudflared service install` registers the binary with NO arguments, so
REM the service starts cloudflared with no command and it exits immediately
REM ("process terminated unexpectedly"). This patch is undocumented in
REM Cloudflare's Windows guide. Idempotent — safe to re-apply on every reinstall.
REM (Discovered 2026-04-30 during initial deployment.)
echo       Patching service ImagePath to include 'tunnel run %TUNNEL_NAME%'...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0fix_cloudflared_imagepath.ps1" -TunnelName "%TUNNEL_NAME%"
if %ERRORLEVEL% neq 0 (
    echo WARNING: ImagePath patch failed. Service may not start automatically.
    echo          Manual fix:
    echo            powershell -File "%~dp0fix_cloudflared_imagepath.ps1" -TunnelName "%TUNNEL_NAME%"
)

net start cloudflared
echo Service installed and started.

REM --- Done ---
echo.
echo ==========================================
echo  Setup Complete!
echo ==========================================
echo.
echo  Dashboard URL: https://%HOSTNAME%
echo  Redirect URL:  https://raanman.lol/bets
echo.
echo  Tunnel name:   %TUNNEL_NAME%
echo  Tunnel ID:     %TUNNEL_ID%
echo  Config file:   %CONFIG_FILE%
echo.
echo  To check status:  cloudflared tunnel info %TUNNEL_NAME%
echo  To view logs:     cloudflared tunnel run %TUNNEL_NAME% (manual mode)
echo  To stop service:  net stop cloudflared
echo  To start service: net start cloudflared
echo.
goto :eof

:error
echo.
echo Setup failed. Please fix the error above and re-run.
exit /b 1
