"""Write signal research Phase 1-2 deliverables."""
import json
import datetime

papers = {
    "date": "2026-05-23",
    "queries_run": [
        "arxiv q-fin: cryptocurrency regime signal",
        "arxiv q-fin: precious metals gold silver forecasting",
        "arxiv q-fin: intermarket cross asset momentum signal",
        "arxiv q-fin: ETH staking exchange flow signal",
        "arxiv q-fin: volatility risk premium trading signal",
        "arxiv: ethereum trading signal on-chain",
        "ssrn: ethereum DeFi trading signal prediction 2025 2026",
        "ssrn: gold silver intermarket cross-asset trading strategy",
        "websearch: quantitative alpha crypto factor model on-chain",
    ],
    "papers_found": [
        {
            "title": "Continuous Timing Signals for Growth-Defensive Style Allocation",
            "authors": "Zheli Xiong",
            "year": 2026,
            "source": "arxiv",
            "url": "https://arxiv.org/abs/2605.20636",
            "citation_count": 0,
            "abstract_summary": "Smooth composite scoring combining rate relief, SPY drawdown depth, high-VIX stress relief, and growth-crowding penalty mapped to allocation weights via tanh. CAGR 19.24%, Sharpe 1.01.",
            "signal_ideas": ["macro_composite_timing_signal", "vix_stress_relief_gate"],
            "relevance": "high",
            "assets": ["cross-asset"],
        },
        {
            "title": "Systematic Trend-Following with Adaptive Portfolio Construction (AdaptiveTrend)",
            "authors": "Unknown",
            "year": 2026,
            "source": "arxiv",
            "url": "https://arxiv.org/abs/2602.11708",
            "citation_count": 0,
            "abstract_summary": "6H trend-following with dynamic trailing stop calibrated to intra-day volatility regimes. Rolling Sharpe asset selection + 70/30 long-short. Sharpe 2.41, MaxDD -12.7%.",
            "signal_ideas": ["adaptive_trailing_stop_momentum"],
            "relevance": "high",
            "assets": ["BTC-USD", "ETH-USD"],
        },
        {
            "title": "Exploring Risk and Return Profiles of Funding Rate Arbitrage",
            "authors": "Unknown",
            "year": 2025,
            "source": "sciencedirect",
            "url": "https://www.sciencedirect.com/science/article/pii/S2096720925000818",
            "citation_count": 0,
            "abstract_summary": "Top-decile funding rate extremes precede 5-10% price retracements 60% of time within 72h. DEX Sharpe 23.55.",
            "signal_ideas": ["funding_extreme_retracement_signal"],
            "relevance": "high",
            "assets": ["BTC-USD", "ETH-USD"],
        },
        {
            "title": "The AutoTune Filter (TASC May 2026)",
            "authors": "John F. Ehlers",
            "year": 2026,
            "source": "tasc_journal",
            "url": "https://financial-hacker.com/the-autotune-filter/",
            "citation_count": 0,
            "abstract_summary": "Rolling autocorrelation detects dominant cycle period. Adaptive bandpass filter tuned dynamically. ROC zero-crossing signals. ES 2010-2025 backtest ~25% CAGR.",
            "signal_ideas": ["autotune_adaptive_cycle"],
            "relevance": "high",
            "assets": ["cross-asset"],
        },
        {
            "title": "Gold Silver Pair Trading - Mean Reversion Strategy Using ML",
            "authors": "Mittal, Mittal",
            "year": 2025,
            "source": "ssrn",
            "url": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5710242",
            "citation_count": 0,
            "abstract_summary": "Kalman filter gold/silver spread + ML regime filter. Sharpe 0.3->0.73. 2015-2025.",
            "signal_ideas": ["gs_kalman_regime"],
            "relevance": "high",
            "assets": ["XAU-USD", "XAG-USD"],
        },
        {
            "title": "Multi-regime Markov-switching Models with Time-Varying Transitions",
            "authors": "Modee, Li, Westgaard, Bethuelsen",
            "year": 2026,
            "source": "arxiv",
            "url": "https://arxiv.org/abs/2605.14976",
            "citation_count": 0,
            "abstract_summary": "Extended GAS-driven transition probabilities across K regimes for Treasury yields.",
            "signal_ideas": ["gas_regime_transition"],
            "relevance": "medium",
            "assets": ["cross-asset"],
        },
        {
            "title": "Quantitative Alpha in Crypto Markets: Systematic Review",
            "authors": "William Mann",
            "year": 2025,
            "source": "ssrn",
            "url": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5225612",
            "citation_count": 0,
            "abstract_summary": "Reviews crypto alpha: cross-exchange arb, factor-based investing, on-chain metrics. Size/momentum/liquidity factors significant.",
            "signal_ideas": ["crypto_factor_composite"],
            "relevance": "medium",
            "assets": ["BTC-USD", "ETH-USD"],
        },
        {
            "title": "Downside Risk Reduction Using Regime-Switching Signals: Statistical Jump Model",
            "authors": "Unknown",
            "year": 2024,
            "source": "arxiv",
            "url": "https://arxiv.org/abs/2402.05272",
            "citation_count": 0,
            "abstract_summary": "Statistical jump model for regime switching applied to downside risk reduction.",
            "signal_ideas": ["jump_regime_risk_reduction"],
            "relevance": "medium",
            "assets": ["cross-asset"],
        },
        {
            "title": "Graph Neural Networks in Financial Time Series Forecasting",
            "authors": "Gregnanin, De Smedt, Gnecco, Parton",
            "year": 2026,
            "source": "arxiv",
            "url": "https://arxiv.org/abs/2605.21192",
            "citation_count": 0,
            "abstract_summary": "GNN geometric patterns yield significant improvements in forecasting accuracy for commodity prices.",
            "signal_ideas": ["gnn_geometric_pattern"],
            "relevance": "low",
            "assets": ["cross-asset"],
        },
    ],
}

web = {
    "date": "2026-05-23",
    "queries_run": [
        "cryptocurrency funding rate divergence trading strategy backtest",
        "silver gold ratio z-score mean reversion trading strategy backtest",
        "continuous timing signal macro regime composite VIX drawdown",
        "ethereum ETH/BTC ratio rotation signal altcoin season",
        "adaptive trailing stop volatility regime crypto ATR calibration",
        "ehlers dominant cycle bandpass filter adaptive 2026 TASC",
        "quantocracy trading signal indicator 2025 2026",
        "bitcoin whale accumulation rate exchange reserve velocity signal",
        "DeFi TVL price divergence ethereum trading signal",
        "macro composite stress indicator NFCI yield curve credit spread",
        "silver industrial demand solar panel supply deficit signal",
        "autocorrelation dominant cycle bandpass filter adaptive python",
        "nansen on-chain ethereum indicator staking flow exchange balance",
        "adaptive momentum lookback window optimization",
        "ETH BTC ratio z-score altcoin rotation signal",
    ],
    "sources_found": [
        {
            "title": "AdaptiveTrend: 6H Trend-Following with Dynamic Trailing Stop",
            "url": "https://arxiv.org/abs/2602.11708",
            "source_type": "academic",
            "signal_ideas": ["adaptive_momentum_trailing_stop"],
            "backtest_results": {"sharpe": 2.41, "max_dd": -0.127, "calmar": 3.18},
            "data_requirements": ["6h OHLCV", "ATR"],
            "relevance": "high",
            "assets": ["BTC-USD", "ETH-USD"],
        },
        {
            "title": "Ehlers AutoTune Filter: Adaptive Cycle Detection + Bandpass",
            "url": "https://financial-hacker.com/the-autotune-filter/",
            "source_type": "blog",
            "signal_ideas": ["autotune_adaptive_cycle_bandpass"],
            "backtest_results": {"cagr": 0.25},
            "data_requirements": ["OHLCV"],
            "relevance": "high",
            "assets": ["cross-asset"],
        },
        {
            "title": "ETH/BTC Ratio Rotation Signal Guide",
            "url": "https://dobermanvc.com/eth-btc-ratio-the-overlooked-rotation-signal-2025-guide/",
            "source_type": "blog",
            "signal_ideas": ["eth_btc_ratio_zscore_rotation"],
            "backtest_results": {},
            "data_requirements": ["OHLCV"],
            "relevance": "high",
            "assets": ["ETH-USD", "BTC-USD"],
        },
        {
            "title": "Funding Rate Extremes: Top Decile Retracement Signal",
            "url": "https://www.sciencedirect.com/science/article/pii/S2096720925000818",
            "source_type": "academic",
            "signal_ideas": ["funding_extreme_contrarian_retracement"],
            "backtest_results": {"win_rate": 0.60, "retracement_pct": "5-10%"},
            "data_requirements": ["funding_rate_8h"],
            "relevance": "high",
            "assets": ["BTC-USD", "ETH-USD"],
        },
        {
            "title": "Continuous Timing Signals: Rate/VIX/Drawdown Composite",
            "url": "https://arxiv.org/abs/2605.20636",
            "source_type": "academic",
            "signal_ideas": ["macro_composite_timing"],
            "backtest_results": {"sharpe": 1.01, "cagr": 0.1924},
            "data_requirements": ["TNX", "SPY", "VIX"],
            "relevance": "high",
            "assets": ["cross-asset"],
        },
        {
            "title": "Bitcoin Whale Accumulation + Exchange Reserve Velocity",
            "url": "https://www.spotedcrypto.com/bitcoin-whale-accumulation-exchange-reserves-2026/",
            "source_type": "industry",
            "signal_ideas": ["whale_exchange_reserve_velocity"],
            "backtest_results": {},
            "data_requirements": ["cryptoquant_api_paid"],
            "relevance": "medium",
            "assets": ["BTC-USD"],
        },
        {
            "title": "Silver Supply Deficit + Solar Demand Structural",
            "url": "https://carboncredits.com/silver-in-2026-and-beyond/",
            "source_type": "industry",
            "signal_ideas": ["silver_supply_deficit_structural"],
            "backtest_results": {},
            "data_requirements": ["manual_data"],
            "relevance": "low",
            "assets": ["XAG-USD"],
        },
    ],
}

with open("data/signal_research_papers.json", "w") as f:
    json.dump(papers, f, indent=2)
with open("data/signal_research_web.json", "w") as f:
    json.dump(web, f, indent=2)
print("Wrote papers + web deliverables")
